{
 "title": "OpenJS World dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Process CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100"
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "latency" }
   ]
  },
  {
   "title": "Number of requests (RPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(requests[5m])" }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nodejs_eventloop_lag_seconds[5m])"
    }
   ]
  },
  {
   "title": "Inflight requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(inflight_requests[5m])"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes" }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Process restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(process_restarts[5m])" }
   ]
  },
  {
   "title": "requests vs. cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(requests[5m])", "legendFormat": "requests" },
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "cpu usage"
    }
   ]
  }
 ]
}